### ISSUE TITLE
Problem connecting to a toy

### ISSUE THREAD

**Issue by Junelicious** [kyrahabattoir/ButtplugWebBridge#1]
Not sure what's the problem but seem to catch this whenever my toy (MagicMotion Solstice) is available for connection. 
```
info: ToyWebBridge.Services.WebsocketService[0]
      Scanning for devices...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ToyWebBridge.Services.DeviceRegister.OnDeviceAdded(ButtplugClientDevice device) in D:\Downloads\ToyWebBridge-master\Services\DeviceRegister.cs:line 49
   at ToyWebBridge.Services.WebsocketService.<StartAsync>b__10_0(Object source, DeviceAddedEventArgs args) in D:\Downloads\ToyWebBridge-master\Services\WebsocketService.cs:line 47
   at Buttplug.ButtplugClient.SorterCallback(UIntPtr buf, Int32 buf_length)
```

**Comment by kyrahabattoir** [comment]
Thanks for the report, I'll look into it.
